### ISSUE TITLE
repl.history 0.1.3 removing or not loading some functions compared to node repl.

### ISSUE THREAD

**Issue by mikemaccana** [eush77/node.history#1]
Example:

```
> nr
> require('es6-shim');
> console.log(Array.prototype.findIndex)
```

Returns undefined.

Running the same JS with `node` 0.12 returns:

```
> [Function: findIndex]
```

**Comment by eush77** [comment]
Thanks for the report!
This was the problem with the global context. Should be fixed in 0.1.3.

**Comment by mikemaccana** [comment]
Thanks for the quick reply! I'm using 0.1.3. Do you mean 0.1.4?

**Comment by eush77** [comment]
It wasn't actually a problem in `repl.history`, but rather in this module. `repl.history` doesn't have to upgrade.
0.1.3 is the version of `node.history` I've just published.
